apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: example-ingress
  annotations:
    ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  - host: kubernetes.docker.internal
    http:
      paths:
        - path: /
          backend:
            serviceName: apple-service
            servicePort: 5678
