pipeline {
    agent {
        kubernetes {
            label 'kubepod'
            defaultContainer 'jnlp'
        }
    }
    
    stages {
//       stage('Manifests Run') {
//           steps{
//               withKubeConfig([credentialsId: 'clusterk8sconfig', serverUrl: 'https://kubernetes.docker.internal:6443']) {
//               sh 'curl -LO "https://storage.googleapis.com/kubernetes-release/release/v1.20.5/bin/linux/amd64/kubectl"'  
//                 sh 'chmod u+x ./kubectl'
//                 sh './kubectl apply -f $WORKSPACE/Kustomize/'    
//               }
//           }
//       }
        stage('Kubernetes Deploy Plugin') {
            steps {
                dir("Kustomize/") {
                    script {
                        kubernetesDeploy(configs: "pod-svc.yaml", kubeconfigId: "mykubeconfig")
                    }
                }
            }
        }
    }
}
