pipeline {
    agent {
        kubernetes {
            label 'kubepod'
            defaultContainer 'jnlp'
        }
    }
    
    stages {
      stage('Sleep for 10 sec to check agent pod creation') {
          steps {
              script {
                sleep(3)      
              }
          }
      }
      stage('Kustomize Run') {
          steps{
              withKubeConfig([credentialsId: 'clusterk8sconfig', serverUrl: 'https://kubernetes.docker.internal:6443']) {
              sh 'curl -LO "https://storage.googleapis.com/kubernetes-release/release/v1.20.5/bin/linux/amd64/kubectl"'  
                sh 'chmod u+x ./kubectl'  
                sh 'pwd'
                  sh 'ls -alh'
                sh './kubectl get pods -A'
                sh './kubectl apply -f $WORKSPACE/Kustomize/'    
              }
          }
      }
    }
}
